Handle error case of missing volume information in the feed
StreamAlpha/tvdatafeed pull request #63
Opened 2022-07-25 05:11 UTC by anshulthakur

Issues #60 and #58 should be fixed with this patch.

2022-07-25 05:43 UTC, abhiquiet commented
@anshulthakur Thanks for the update, but when I am reinstalling the TvDataFeed using the following command, ```

!pip uninstall TvDatafeed -y
!pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
```
I am getting the same error for fetching the NIFTY data. 
Kindly guide me on how to update the latest code?

2022-07-25 06:57 UTC, anshulthakur commented
> @anshulthakur Thanks for the update, but when I am reinstalling the TvDataFeed using the following command, ```
> 
> !pip uninstall TvDatafeed -y !pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
> 
> ```
> I am getting the same error for fetching the NIFTY data. 
> Kindly guide me on how to update the latest code?
> ```

Hi @abhiquiet this version (of handling volume issue) is currently pending merge. The version you are referring to handles the issue of auto-login.

2022-07-26 03:40 UTC, abhiquiet commented
@anshulthakur, as suggested, I tried uninstalling the TVDataFeed and installing it from the code. But I was not successful again. 
I am new to GitHub usage and implementations. Can you please guide how to install it on Ubuntu 20.04? 
I will be obliged.

2022-07-26 06:37 UTC, anshulthakur commented
> @anshulthakur, as suggested, I tried uninstalling the TVDataFeed and installing it from the code. But I was not successful again. I am new to GitHub usage and implementations. Can you please guide how to install it on Ubuntu 20.04? I will be obliged.

Try using:
`pip install git+https://github.com/StreamAlpha/tvdatafeed.git@main`

2022-07-26 07:42 UTC, abhiquiet commented
@anshulthakur Thanks for such quick response. 
I tried implementing the code, based on your input, 
The error reduced, but still I am not able to login. I am getting the following error now 
```

ERROR:tvDatafeed.main:Service.__init__() got an unexpected keyword argument 'verbose'
ERROR:tvDatafeed.main:'NoneType' object has no attribute 'find_element', ("'NoneType' object has no attribute 'find_element'",)
ERROR:tvDatafeed.main:automatic login failed
 Reinitialize tvdatafeed with auto_login=False 
WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited
```
I was able to fetch data for the scripts, but was getting error for NIFTY. 
When I am trying to fetch data for NIFTY I am getting following error. 
```

File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:510, in TvDatafeed.get_hist(self, symbol, exchange, interval, n_bars, fut_contract, extended_session)
    507     if "series_completed" in result:
    508         break
--> 510 return self.__create_df(raw_data, symbol)

File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:382, in TvDatafeed.__create_df(raw_data, symbol)
    373     xi = re.split("\[|:|,|\]", xi)
    374     ts = datetime.datetime.fromtimestamp(float(xi[4]))
    375     data.append(
...
    387     data, columns=["datetime", "open", "high", "low", "close", "volume"]
    388 ).set_index("datetime")
    389 data.insert(0, "symbol", value=symbol)

ValueError: could not convert string to float: '}'
```

Can you please guide on both the issues?

I will be highly obliged. 

Regards

2022-07-26 08:01 UTC, anshulthakur commented
> @anshulthakur Thanks for such quick response. I tried implementing the code, based on your input, The error reduced, but still I am not able to login. I am getting the following error now
> 
> ```
> 
> ERROR:tvDatafeed.main:Service.__init__() got an unexpected keyword argument 'verbose'
> ERROR:tvDatafeed.main:'NoneType' object has no attribute 'find_element', ("'NoneType' object has no attribute 'find_element'",)
> ERROR:tvDatafeed.main:automatic login failed
>  Reinitialize tvdatafeed with auto_login=False 
> WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited
> ```
> 
> I was able to fetch data for the scripts, but was getting error for NIFTY. When I am trying to fetch data for NIFTY I am getting following error.
> 
> ```
> 
> File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:510, in TvDatafeed.get_hist(self, symbol, exchange, interval, n_bars, fut_contract, extended_session)
>     507     if "series_completed" in result:
>     508         break
> --> 510 return self.__create_df(raw_data, symbol)
> 
> File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:382, in TvDatafeed.__create_df(raw_data, symbol)
>     373     xi = re.split("\[|:|,|\]", xi)
>     374     ts = datetime.datetime.fromtimestamp(float(xi[4]))
>     375     data.append(
> ...
>     387     data, columns=["datetime", "open", "high", "low", "close", "volume"]
>     388 ).set_index("datetime")
>     389 data.insert(0, "symbol", value=symbol)
> 
> ValueError: could not convert string to float: '}'
> ```
> 
> Can you please guide on both the issues?
> 
> I will be highly obliged.
> 
> Regards

For Issue 1, I think you need to update selenium:

`pip install selenium --upgrade`

For second, the pull request is pending. You can make the changes manually following the currently pending pull request #63 by observing the diff.

2022-07-27 09:25 UTC, sukhneerguron requested changes

2022-07-27 09:25 UTC, sukhneerguron commented on tvDatafeed/main.py
> +                time.sleep(1)
why this change ?

2022-07-27 09:25 UTC, sukhneerguron commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
breaking sandbox can be problematic when running on host machine.
instead, detect if code is running in a container
```
def in_container():
    with open('/proc/1/cgroup', 'rt') as proc_one:
        prog =  proc_one.read()
        if prog in ["docker", "lxc", "kubepod", "kubepods"]
             return True
        return False
```

2022-07-27 09:25 UTC, sukhneerguron commented on tvDatafeed/main.py
> +            if int(selenium.__version__.split('.')[0])>=4:
This is not really a good way. Can you fix the version that you want in requirements.txt

2022-07-27 09:25 UTC, sukhneerguron commented on tvDatafeed/main.py
> +                time.sleep(2)
why ?

2022-07-27 11:18 UTC, anshulthakur commented on tvDatafeed/main.py
> +                time.sleep(1)
5 seconds was too large a wait. It is not invoking any js, only a CSS selector is being invoked. Hence, decreased sleep time to increase responsiveness.

2022-07-27 11:19 UTC, anshulthakur commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
Yes, but it is noted in various places that chromedriver sometimes fails to launch chrome if these options are not enabled (as in my case). I'll revert these particular changes under the assumption that it works for everyone else.

2022-07-27 11:24 UTC, anshulthakur commented on tvDatafeed/main.py
> +            if int(selenium.__version__.split('.')[0])>=4:
selenium 4 may not be available for various distros. For example, machines not having python > 3.6 typically don't install selenium 4 (using pip install selenium). So, this was added to handle both worlds.

2022-07-27 11:25 UTC, anshulthakur commented on tvDatafeed/main.py
> +                time.sleep(2)
Mainly to decrease response time. But okay, here, I'll revert it to 5 as a new page is being opened.

2022-07-27 11:28 UTC, sukhneerguron commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
yes, these options are needed when the code is executing inside a docker container. Since docker is already sandboxed chrome launch will fail as docker wont allow it to sandbox further. I would suggest to keep these opts and only add when docker is detected.

2022-07-27 11:29 UTC, anshulthakur commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
Yes, will add your suggested changes and update the PR.

2022-07-27 11:40 UTC, sukhneerguron commented on tvDatafeed/main.py
> +            if int(selenium.__version__.split('.')[0])>=4:
@StreamAlpha is there is a larger support window planned? and a plan for legacy support ? 
imo Since the HTML page can change often (leading to breaking versions) we should use that event as a driver to push people to update to the latest version.

2022-07-27 11:41 UTC, sukhneerguron commented on tvDatafeed/main.py
> +                time.sleep(1)
okay this makes sense. You can drop the window size.

2022-07-27 11:45 UTC, sukhneerguron commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
I am not 100% confident on in the container detect code. I mostly wrote it from memory. Maybe you will have to do the opposite ie check if docker, lxc etc is in prog

2022-07-27 13:47 UTC, anshulthakur commented on tvDatafeed/main.py
> +        options.add_argument("--disable-dev-shm-usage")
I've put this code as is, along with detection for WSL2 (which I've tested). You can review the changes.

2022-08-06 19:14 UTC, StreamAlpha commented
fixed in v2.0.0

2022-08-06 19:14 UTC, closed without merging